import { chromium } from "playwright";
const b = await chromium.launch({ headless: true });
const ctx = await b.newContext({ viewport: { width: 1440, height: 1000 } });
const p = await ctx.newPage();
const errs = [];
p.on("console", (m) => { if (m.type() === "error") errs.push(m.text().slice(0, 90)); });
p.on("pageerror", (e) => errs.push("PAGEERROR:" + e.message.slice(0, 90)));
await p.goto("http://localhost:3000", { waitUntil: "networkidle", timeout: 30000 });
await p.waitForTimeout(3000);
const hyd = errs.filter((e) => /hydrat/i.test(e));
console.log("total console errors:", errs.length, "| hydration:", hyd.length);
if (hyd.length) console.log("HYDRATION:", hyd[0]);
if (errs.length) console.log("ALL:", JSON.stringify(errs.slice(0, 5)));
await b.close();
