const DISPLAY_NAMES: Record<string, string> = {
  // Image integrity
  ela_full_image: "Error Level Analysis",
  ela_anomaly_classify: "ELA Anomaly Classification",
  neural_ela: "Neural ELA",
  jpeg_ghost_detect: "JPEG Ghost Detection",
  frequency_domain_analysis: "Frequency Domain Analysis",
  deepfake_frequency_check: "Deepfake Frequency Check",
  perceptual_hash: "Perceptual Hash",
  file_hash_verify: "File Hash Verification",
  analyze_image_content: "Semantic Classification",
  extract_text_from_image: "OCR Text Extraction",
  extract_evidence_text: "OCR Text Extraction",
  noise_fingerprint: "PRNU Noise Fingerprint",
  noiseprint_cluster: "Sensor Clustering",
  neural_fingerprint: "Neural Fingerprint",
  copy_move_detect: "Copy-Move Clone Detection",
  neural_copy_move: "Neural Copy-Move",
  splicing_detect: "Splicing Detection",
  neural_splicing: "Neural Splicing (TruFor)",
  anomaly_tracer: "ManTra-Net Anomaly Tracer",
  f3_net_frequency: "F3-Net GAN Artifact",
  diffusion_artifact_detector: "Diffusion Artifact Detector",
  synthid_watermark_detect: "SynthID / AI Watermark",
  adversarial_robustness_check: "Anti-Forensics Check",
  adversarial_robustness: "Anti-Forensics Check",
  roi_extract: "Region of Interest",
  // Scene / object
  object_detection: "Object Detection",
  secondary_classification: "Secondary Classification",
  scale_validation: "Scale Validation",
  lighting_consistency: "Lighting Consistency",
  lighting_correlation_initial: "Lighting Correlation",
  scene_incongruence: "Scene Coherence Check",
  contraband_database: "Contraband Screen",
  vector_contraband_search: "Contraband Screen",
  screenshot_scene_applicability: "Scene Applicability",
  screenshot_layout_forensics: "Layout Forensics",
  // Audio
  speaker_diarize: "Speaker Diarization",
  neural_prosody: "Neural Prosody Analysis",
  prosody_analyze: "Prosody Analysis",
  audio_gen_signature: "TTS Signature Detector",
  voice_clone_detect: "Voice Clone Screen",
  anti_spoofing_detect: "Anti-Spoofing Screen",
  codec_fingerprinting: "Codec Fingerprint",
  audio_visual_sync: "AV Sync Verification",
  av_sync_verify: "AV Sync Verification",
  audio_splice_detect: "Audio Splice Detector",
  enf_analysis: "ENF Frequency Analysis",
  background_noise_analysis: "Background Noise Analysis",
  voice_clone_deep_ensemble: "Voice Clone (Deep Ensemble)",
  anti_spoofing_deep_ensemble: "Anti-Spoofing (Deep Ensemble)",
  // Video
  video_metadata: "Video Stream Probe",
  video_metadata_extract: "Video Metadata",
  vfi_error_map: "Motion Interpolation Errors",
  thumbnail_coherence: "Thumbnail Coherence",
  frame_consistency_analysis: "Frame Consistency",
  optical_flow_analysis: "Optical Flow Analysis",
  optical_flow_analyze: "Optical Flow Analysis",
  interframe_forgery_detector: "Interframe Forgery",
  frame_extraction: "Frame Extraction",
  frame_window_extract: "Frame Extraction",
  face_swap_detection: "Face-Swap Detection",
  face_swap_detect: "Face-Swap Detection",
  rolling_shutter_validation: "Rolling Shutter Validation",
  compression_artifact_analysis: "Compression Artifacts",
  // Metadata / provenance
  exif_extract: "EXIF Metadata Extraction",
  metadata_anomaly_score: "Metadata Anomaly Score",
  metadata_anomaly_scorer: "Metadata Anomaly Score",
  exif_isolation_forest: "EXIF Outlier Detection",
  gps_timezone_validate: "GPS–Timezone Consistency",
  steganography_scan: "Steganography Scan",
  file_structure_analysis: "Binary Structure Analysis",
  hex_signature_scan: "Hex Signature Scan",
  timestamp_analysis: "Timestamp Analysis",
  astro_grounding: "Astronomical Grounding",
  astronomical_api: "Astronomical Grounding",
  camera_profile_match: "Camera Profile Match",
  provenance_chain_verify: "Provenance Chain Verification",
  prnu_sensor_verification: "PRNU Sensor Verification",
  prnu_analysis: "PRNU Analysis",
  compression_risk_audit: "Compression Audit",
  extract_deep_metadata: "Deep Metadata Extraction",
  device_fingerprint_db: "Device Fingerprint DB",
  c2pa_verify: "C2PA Provenance",
  c2pa_validator: "C2PA Provenance",
  mediainfo_profile: "Container Profile (MediaInfo)",
  av_file_identity: "AV File Identity",
  // Synthesis
  gemini_deep_forensic: "Gemini Visual Forensics",
  inter_agent_call: "Cross-Agent Coordination",
};

export function fmtTool(raw: string): string {
  if (!raw) return "";
  const clean = raw.trim();
  if (DISPLAY_NAMES[clean]) return DISPLAY_NAMES[clean];
  return clean
    .replace(/_/g, " ")
    .toLowerCase()
    .replace(/\b\w/g, (c) => c.toUpperCase());
}
