import {
  ImageIcon,
  Eye,
  Activity,
  Brain,
  Hash,
  Fingerprint,
  FileSearch,
  Gauge,
  Crosshair,
  Layers,
  Shield,
  Database,
  Scan,
  Search,
  Cpu,
  Zap,
  Wifi,
  Globe,
  Binary,
  Clock,
  type LucideIcon
} from "lucide-react";

export const TOOL_ICONS: Record<string, LucideIcon> = {
  ela_full_image: ImageIcon,
  ela_anomaly_classify: Scan,
  jpeg_ghost_detect: Eye,
  frequency_domain_analysis: Activity,
  deepfake_frequency_check: Brain,
  perceptual_hash: Hash,
  file_hash_verify: Fingerprint,
  analyze_image_content: Eye,
  extract_text_from_image: FileSearch,
  extract_evidence_text: FileSearch,
  noise_fingerprint: Gauge,
  copy_move_detect: Crosshair,
  splicing_detect: Layers,
  adversarial_robustness_check: Shield,
  sensor_db_query: Database,
  prnu_analysis: Fingerprint,
  cfa_demosaicing: Scan,
  gemini_deep_forensic: Brain,
  object_detection: Search,
  secondary_classification: Cpu,
  scale_validation: Gauge,
  lighting_consistency: Zap,
  scene_incongruence: Eye,
  contraband_database: Database,
  object_text_ocr: FileSearch,
  document_authenticity: FileSearch,
  image_splice_check: Layers,
  inter_agent_call: Wifi,
  exif_extract: Hash,
  metadata_anomaly_score: Brain,
  gps_timezone_validate: Globe,
  steganography_scan: Binary,
  file_structure_analysis: Layers,
  hex_signature_scan: Binary,
  timestamp_analysis: Clock,
  astronomical_api: Globe,
  reverse_image_search: Search,
  device_fingerprint_db: Fingerprint,
  c2pa_verify: Shield,
  thumbnail_mismatch: ImageIcon,
  extract_deep_metadata: Hash,
  get_physical_address: Globe,
  mediainfo_profile: Activity,
  av_file_identity: Activity,
};

export function getToolIcon(toolName: string): LucideIcon {
  return TOOL_ICONS[toolName] || Cpu;
}
